version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   wordpress:
     image: wordpress:latest
     ports:
       - 80:80
       - 443:443
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     depends_on:
       - db
volumes:
    db_data:
